#!/usr/bin/env ruby

# Git pre-commit hook that catches errors that I commonly make.
#
# To intentionally ignore the hook (i.e., when adding an alert call), commit
# from the command line with "--no-verify"
#
# Loosely based on Henrik Nyh's <http://henrik.nyh.se> work (2011-10-08)
# under the MIT License.
#
# Bob Gilmore (dev@bobgilmore.name)

load "#{File.dirname(__FILE__)}/pre_commit_helper.rb"
load "#{File.dirname(__FILE__)}/strict_paren_spacing_checker.rb"
load "#{File.dirname(__FILE__)}/alert_checker.rb"

include PreCommitHelper

############# CONFIGURATION

# The two sections of regular expressions below ("forbidden" and "warning")
# will trigger a commit failure, *if* they are found on an added or edited line.

# "Forbidden" regular expressions
FORBIDDEN_STRINGS = [
  /TMP_DEBUG/, # My TextExpander macros for embedding debug code always include this for easy scanning.
  />>>>>>/,    # Git conflict markers
  /<<<<<</,    # "
  /binding\.pry/,        # pry debugging code
  /binding\.remote_pry/, # "
  /save_and_open_page/,  # Launchy debugging code
  /debugger/,      # Ruby < 2.0 debugging code, JS debugging code.
  /byebug/,        # Ruby >= 2.0 debugging code
  /logger\.debug/, # I almost never want to commit a (Ruby) call to logger.debug.  error, message, etc., but not debug.
  /====/,          # Git merge conflict marker
  /save_and_open_screenshot/, # Capybara debugging
  /save_screenshot/,          # "
  /save_and_open_page/        # "
]

NON_CHECKED_FILE_EXTENSIONS = [
  '.md',
  '.mmd',
  '.txt'
]

FORBIDDEN_STRINGS_EXCEPT_IN_NODE = [
  /console\.\w*/,  # JavaScript debug code that would break IE.
]

USER = ENV["USER"]
USER_HOME = [
  Regexp.new("/home/#{USER}"),        # Hard-coded path to user's HOME
  Regexp.new("/Users/#{USER}"),       # ''
  Regexp.new("/export/home/#{USER}")  # '' (for a current work config)
]

# Warning signs that someone is committing a private key
PRIVATE_KEY_INDICATORS = [
  /PRIVATE KEY/,
  /ssh-rsa/
]

# For particular projects - configurable on a per-project git config basis

# Prevent inadvertent .ruby-version and .rbenv-version commits.  I rarely edit these files, so any attempt to commit is probably an accident.
ALLOW_RUBY_VERSION_CHANGES_CONFIG = `git config hooks.allowrubyversionchange`.strip
FORBID_RUBY_VERSION_CHANGES = ALLOW_RUBY_VERSION_CHANGES_CONFIG.empty? || (ALLOW_RUBY_VERSION_CHANGES_CONFIG != 'true')

# Check syntax of Ruby files.  Deactivate if your git app of choice uses a version of Ruby that doesn't support your project.
# (i.e., on old Mac OS, apps will use Ruby 1.8, which is unaware of the Ruby 1.9 JS hash syntax.)
CHECK_RUBY_CONFIG = `git config hooks.checkrubysyntax`.strip
CHECK_RUBY_SYNTAX = CHECK_RUBY_CONFIG.empty? || (CHECK_RUBY_CONFIG == 'true')

############# END OF CONFIGURATION

# Check for "forbidden" and "warning" strings

# Loop over ALL errors and warnings and return ALL problems.
# I want to report on *all* problems that exist in the commit before aborting,
# so that anyone calling --no-verify has been informed of all problems first.
error_found = false

full_diff = `git diff --cached --`.encode("UTF-8")

full_diff.scan(%r{^\+\+\+ b/(.+)\n@@.*\n([\s\S]*?)(?:^diff|\z)}).each do |file, diff|
  changed_code_for_file = diff.split("\n").select { |x| x.start_with?("+") }.join("\n")

  # Scan for private key indicators
  PRIVATE_KEY_INDICATORS.each do |re|
    if changed_code_for_file.match(re)
      puts %{Error: git pre-commit hook detected a probable private key commit: "#{$1 || $&}" to #{file}\n--------------}
      error_found = true
    end
  end

  unless NON_CHECKED_FILE_EXTENSIONS.include? File.extname(file)
    changed_lines_for_file = diff.split("\n").select { |x| x.start_with?("+") }
    dir = File.dirname(file)

    # Scan for "forbidden" calls
    FORBIDDEN_STRINGS.each do |re|
      if changed_code_for_file.match(re)
        puts %{Error: git pre-commit hook forbids committing "#{$1 || $&}" to #{file}\n--------------}
        error_found = true
      end
    end

    # Scan for "forbidden except in node" calls
    unless PreCommitHelper::project_type == 'node'
      FORBIDDEN_STRINGS_EXCEPT_IN_NODE.each do |re|
        if changed_code_for_file.match(re)
          puts %{Error: git pre-commit hook forbids committing "#{$1 || $&}" to #{file} outside of Node.js projects. If this *is* a Node project, run}
          puts %{\nnpm init\n\nat the top level of the project to add a package.json file. See\nhttps://devcenter.heroku.com/articles/getting-started-with-nodejs#declare-dependencies-with-npm\nfor more information.}
          puts %{--------------}
          error_found = true
        end
      end
    end

    # Scan for probable HARD_CODED references to user's home directory
    USER_HOME.each do |re|
      if changed_code_for_file.match(re)
        puts %{Error: git pre-commit hook forbids committing what looks like a hard-coded home dir: "#{$1 || $&}" to #{file}\n--------------}
        error_found = true
      end
    end

    PreCommitHelper::run_checker(AlertChecker, dir, file, changed_code_for_file)
    PreCommitHelper::run_checker(StrictParenSpacingChecker, dir, file, changed_code_for_file )

  end
end

name_only_array = `git diff --cached --name-only`.split(/\n/)

# Syntax check .rb files.
if CHECK_RUBY_SYNTAX
  toplevel = `git rev-parse --show-toplevel`
  name_only_array.each do |fil|
    if File.extname(fil) == '.rb'
      fullfile = File.join(toplevel.strip, fil)
      if File.exist?(fullfile)
        output = `ruby -c #{fullfile}`
        status = $?.success?
        unless status
          puts %{Error: git pre-commit hook found a syntax error in #{fullfile}.\nIf you find that this check is flagging valid code too often, you may be using an old system git to perform the syntax check.}
          puts deactivation_message("deactivate the syntax check", "checkrubysyntax", false)
          error_found = true
        end
      end
    end
  end
end

# Prevent changes to .ruby-version (and .rbenv-version)
if FORBID_RUBY_VERSION_CHANGES
  name_only_array.each do |fil|
    base = File.basename(fil)
    if base == '.ruby-version' || base == '.rbenv-version'
      puts %{Warning: git pre-commit hook found attempt to edit #{fil}.\nThis may be OK, or not, depending on your project requirements.}
      puts deactivation_message("allow", "allowrubyversionchange", true)
      error_found = true
    end
  end
end

# Finally, report errors
if error_found
  puts "To commit anyway, use --no-verify"
  exit 1
end
