#!/usr/bin/env ruby

# Git pre-commit hook that catches errors that I commonly make.
#
# To intentionally ignore the hook (i.e., when adding an alert call), commit
# from the command line with "--no-verify"
#
# Loosely based on Henrik Nyh's <http://henrik.nyh.se> work (2011-10-08)
# under the MIT License.
#
# Bob Gilmore (dev@bobgilmore.name)

$:.unshift File.dirname(__FILE__)
$:.unshift "#{File.dirname(__FILE__)}/pre_commit"

require "pre_commit_helper.rb"
require "checker_results.rb"
Dir[File.dirname(__FILE__) + "/pre_commit/checkers/*_checker.rb"].each { |f| load f }

include PreCommitHelper

NON_CHECKED_FILE_EXTENSIONS = [
  '.md',
  '.mmd',
  '.txt'
]

NON_CHECKED_FILE_NAMES = [
  'Gemfile',
  'Gemfile.lock'
]

PROJECT_TYPE = PreCommitHelper::project_type

res = CheckerResults.new

# Loop over ALL errors and warnings and return ALL problems.
# I want to report on *all* problems that exist in the commit before aborting,
# so that anyone calling --no-verify has been informed of all problems first.

full_diff = `git diff --cached --`.encode("UTF-8")

full_diff.scan(%r{^\+\+\+ b/(.+)\n@@.*\n([\s\S]*?)(?:^diff|\z)}).each do |file, diff|
  unless (NON_CHECKED_FILE_NAMES.include?(file) || NON_CHECKED_FILE_EXTENSIONS.include?(File.extname(file)))
    dir = File.dirname(file)
    
    changed_code_for_file = diff.split("\n").select { |x| x.start_with?("+") }.join("\n")

    res.record(AlertChecker.new(directory: dir, file: file, changes: changed_code_for_file, project_type: PROJECT_TYPE))
    res.record(ForbiddenStringChecker.new(file: file, changes: changed_code_for_file, project_type: PROJECT_TYPE))
    res.record(PrivateKeyChecker.new(directory: dir, file: file, changes: changed_code_for_file, project_type: PROJECT_TYPE))
    res.record(RspecExpectToReceiveChecker.new(directory: dir, file: file, changes: changed_code_for_file, project_type: PROJECT_TYPE))
    res.record(RspecIsExpectedToChecker.new(directory: dir, file: file, changes: changed_code_for_file, project_type: PROJECT_TYPE))
    res.record(RspecShouldEqualChecker.new(directory: dir, file: file, changes: changed_code_for_file, project_type: PROJECT_TYPE))
    res.record(RspecToNotChecker.new(directory: dir, file: file, changes: changed_code_for_file, project_type: PROJECT_TYPE))
    res.record(RubyNoThrowChecker.new(directory: dir, file: file, changes: changed_code_for_file, project_type: PROJECT_TYPE))
    res.record(StrictParenSpacingChecker.new(directory: dir, file: file, changes: changed_code_for_file, project_type: PROJECT_TYPE))
    res.record(UserHomeChecker.new(directory: dir, file: file, changes: changed_code_for_file, project_type: PROJECT_TYPE))
  end
end

name_only_array = `git diff --cached --name-only`.split(/\n/)
toplevel = `git rev-parse --show-toplevel`

res.record(SyntaxRubyChecker.new(toplevel: toplevel, files: name_only_array, project_type: PROJECT_TYPE))
res.record(RubyVersionChecker.new(files: name_only_array, project_type: PROJECT_TYPE))

# Report errors and fail the commit if necessary
if res.errors?
  puts(res)
  puts "To commit anyway, use --no-verify"
  exit 1
end
